ДЗ2
Janko025/2022-2-VK-EDU-FS-Frontend-G-Fedotov pull request #1
Opened 2022-10-23 12:26 UTC by Janko025

#Домашнее задание №2

Прошу @martinkomitsky или @haseprogram проверить его.

Что было сделано:
*
*
*

Вопрос:
- я вот когда пушу дз через macos мне выдает такую ошибку и запрещает [https://ibb.co/5BbNHhS](url), а вот через винду все нормально пушится. Почему такое может происходить?

2022-10-24 11:47 UTC, martinkomitsky commented
> * я вот когда пушу дз через macos мне выдает такую ошибку и запрещает [https://ibb.co/5BbNHhS](url), а вот через винду все нормально пушится. Почему такое может происходить?

Без понятия. Не знаю, как ты к этому состоянию пришел. Возможно, есть какие-то косяки в файле для github actions.
Можно посмотреть тут https://github.com/orgs/community/discussions/26254

2022-10-24 11:48 UTC, martinkomitsky requested changes
У тебя задеплоен readme, а не страничка
https://janko025.github.io/2022-2-VK-EDU-FS-Frontend-G-Fedotov/

2022-10-24 22:41 UTC, Janko025 commented
Исправил!  @martinkomitsky или @HaseProgram 
P.S. 
Почему вот в файле index.js есть в первой строке => import './index.css'; Я его сначала удалил так как не понял зачем это вообще нужно, потом когда деплоилось приложение на git page. у меня приложение было без функционала.
Потом вспомнил это, вернул обратно, сначала запустил на локалке =>  у меня страница при вводе в форму и нажатие enter просто обновлялась.    А когда запушил и задеплоил все стало работать.  Почему так происходит?

2022-10-25 09:50 UTC, martinkomitsky commented
> Потом вспомнил это, вернул обратно, сначала запустил на локалке => у меня страница при вводе в форму и нажатие enter просто обновлялась. А когда запушил и задеплоил все стало работать. Почему так происходит?

Без js и выполнения в нем `event.preventDefault()` – это стандартное поведение. Можно прочитать подробнее вот тут
https://stackoverflow.com/questions/63509328/understanding-html-form-element-behavior

2022-10-25 09:51 UTC, martinkomitsky approved these changes
7

2022-10-25 09:51 UTC, merged